### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by b1ack0p** [raspberrypi-ui/gtk2-engines-pixflat#1]
Hi.
Could you please give clear installation instructions for gt2-engines-pixflat? i am trying to make it on Debian11/Xfce which has automake v.1.16 > v1.7 but still giving error. I edited autogen.sh for v.1.16 then i could run automake but still instructions are unclear at readme.md. If possible i would like to get this lovely theme on Xfce. i am trying to modify it.

kind regards

**Comment by spl237** [comment]
In the project directory, do:

mkdir m4
autoreconf -i -f
intltoolize -c --automake --force
rm -rf autom4te.cache
./configure --prefix=/usr --libdir=/usr/lib/arm-linux-gnueabihf
make
